# Generated by Django 4.0.3 on 2022-03-10 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_followers_alter_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='images/logo.png', null=True, upload_to=''),
        ),
    ]
