# Generated by Django 4.0.3 on 2022-03-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_followings_alter_customuser_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followings',
        ),
    ]
