# Generated by Django 4.0.3 on 2022-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_socials_customuser_about_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
