# Generated by Django 4.0.3 on 2022-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='profile.jpeg', null=True, upload_to='profiles'),
        ),
    ]
