# Generated by Django 4.0.3 on 2022-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(to='blog.ipaddresses'),
        ),
    ]
