# Generated by Django 4.0.3 on 2022-03-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ipaddresses_remove_article_views_article_hits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPAddresses',
            new_name='IPAddress',
        ),
    ]
