# Generated by Django 4.0.3 on 2022-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_link',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
