# Generated by Django 4.0.3 on 2022-06-06 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_alter_article_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
