# Generated by Django 4.0.3 on 2022-07-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_article_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='profile.jpeg', null=True, upload_to='images'),
        ),
    ]
